### PR TITLE
Fixing lgtm override option

### PR DESCRIPTION
**Pull request by mahimachander**
Fix to https://github.com/ayazhafiz/slide/pull/132#discussion_r443301739

### CODE REVIEW

**Comment by ayazhafiz** [comment]
lgtm

**Comment by ayazhafiz** [comment]
bruh idk how i feel about all this anime

**Comment by mahimachander** [comment]
i'm a bit spooked

**Comment by ayazhafiz** [comment]
probably should switch to giphy, it looks more reasonable: https://giphy.com/search/lgtm

nothing wrong with anime there’s just a lot of it

**Pull request merged**
