### PR TITLE
quick add refactor

### PR DESCRIPTION
**Pull request by luke-bhan**
Flipped the dec vector so that we can work with subtraction and so that its consistent with the int vector.

### CODE REVIEW

**Comment by luke-bhan** [comment]
So the subtraction dec vec doesn't need to be flipped since the carry is propogated in the other direction then the addmethod. And I think its much cleaner to keep them consistent.

**Comment by ayazhafiz** [comment]
Wait, how? I thought the carry is propogated the same way (right to left). Anyway, I think it would be clearer if you open a PR for the sub method and add this change there for more context.

**Comment by luke-bhan** [comment]
Ok, Quick question. I have a leading zeros problem. So 10-1 = 09. How should we go about handling this in your opinion?

**Comment by ayazhafiz** [comment]
I think I'm confused. Can you give me a bigger example with two numbers?

**Comment by luke-bhan** [comment]
1000 - 999 = 0001

**Comment by luke-bhan** [comment]
I think truncate is the way to go

**Comment by ayazhafiz** [comment]
Ohh.. yeah thats unfortunate

**Comment by ayazhafiz** [comment]
Just shift to the front and pop off remaining elements

**Comment by ayazhafiz** [comment]
`pop` will not deallocate: https://doc.rust-lang.org/src/alloc/vec.rs.html#1195-1204

**Comment by ayazhafiz** [comment]
Maybe even easier: reverse, pop, reverse

**Comment by luke-bhan** [comment]
No, we don't need to reverse, our vec is stored for 01000 as 00010. So the zeros are at the end. Thats why I think we can use truncate. It aslso doesnt truncate.

**Comment by ayazhafiz** [comment]
okay sounds good

**Pull request closed without merging**
