### PR TITLE
Parser update

### PR DESCRIPTION
**Pull request by luke-bhan**
Added parsing from the left. Sorry it took me a while to solve this one. I only ended up adding a few lines and expanding all the macros. I think it can be cleaned up macro wise but I am still do not understand them well so if you want to go for it. Had to change tests in partial_evaluator as well since we left parse now.  @ayazhafiz

### CODE REVIEW

**Comment by ayazhafiz** [comment]
Here is a simpler way to implement binary expressions you may want to consider: https://github.com/ayazhafiz/TypeScript/blob/95cc1c279ef8531b88f0a770ffad0b43ad9249d3/src/compiler/parser.ts#L4031

**Comment by luke-bhan** [comment]
the above implementation is the exact same thing, just broken into separate parts. I will try and make this a more concise macro later today so its all one part

**Comment by ayazhafiz** [comment]
Cool sounds good.

**Comment by ayazhafiz** [comment]
@luke-bhan are you still planning to update this PR?

**Comment by luke-bhan** [comment]
yes, but I haven't started on it if you wanted to do osmething else

**Comment by ayazhafiz** [comment]
You're good. Let me know

**Comment by luke-bhan** [comment]
@ayazhafiz PTAL, also I don't know how to combine this to one commit.

**Comment by luke-bhan** [comment]
Theres an issue with the squashed script @ayazhafiz. Take a look at git branch --show-current. It does not exist as a command

**Comment by ayazhafiz** [comment]
You need at least git 2.22:
https://stackoverflow.com/questions/1417957/show-just-the-current-branch-in-git/55088865#55088865

**Pull request merged**
