### PR TITLE
Add subtractive identity rule

### PR DESCRIPTION
**Pull request by ayazhafiz**
Whether this is equivalent to the additive identity, I'm not sure. Would
love some insight here.

Part of #89

### CODE REVIEW

**Comment by luke-bhan** [comment]
hey I’m in bed about to sleep but I’ll give A thorough review tomorrow sorry

**Comment by ayazhafiz** [comment]
you're good, sleep tight!

**Comment by luke-bhan** [comment]
what happens if you try to add the rule a + 1 - 1. Does it simplify to a + 0 or no? Probably not I would guess

**Comment by ayazhafiz** [comment]
yeah it doesnt simplify at all...

**Pull request merged**
