### PR TITLE
Do not clone int during bignum creation

### PR DESCRIPTION
**Pull request by ayazhafiz**
The vec is only used once here, so just move it into the iterator rather
than making a new allocation.

### CODE REVIEW

**Comment by luke-bhan** [comment]
We neecd to change the add method as well

**Comment by ayazhafiz** [comment]
This doesn't change the implementation, it's all the same

**Comment by luke-bhan** [comment]
No, I understand that. I am saying I use the same cloning form in the add method and we should refactor that with this pr now too

**Comment by ayazhafiz** [comment]
Do you? I didn’t see it

**Pull request merged**
