### PR TITLE
logo?

### PR DESCRIPTION
**Pull request by ayazhafiz**
Just playing around... here are some ideas. @luke-bhan let me know what
you think.

opt-1

---

opt-2

---

opt-3

---

opt-4

### CODE REVIEW

**Comment by luke-bhan** [comment]
They're very nice. I like the third one the best! Do you think we should have it as an arrow so x/x -> 1

**Comment by ayazhafiz** [comment]
Oh, I was thinking more like `x/x - 1` goes down the slide. do you think there should be something on the other side?

**Comment by ayazhafiz** [comment]
> Also, it hurts me to see you did this in latex. You can use illustrator or something to be much faster

Yeah, I just want to make it easy to edit...

**Comment by luke-bhan** [comment]
See, I completely missed them going down the slide. Hmm. I think there should be something but I am not sure.

**Comment by luke-bhan** [comment]
Wait, what if you did x/x at the top of the slide and then 1 at the bottom or seomthing like that

**Comment by ayazhafiz** [comment]
@luke-bhan what do you think of

logo

**Comment by ayazhafiz** [comment]
A simpler version:

image

**Comment by luke-bhan** [comment]
I like it

**Comment by ayazhafiz** [comment]
> I like it

Which one?

**Comment by luke-bhan** [comment]
definitely the second one. I think turning it into this could be better. 2(x-x)/4 = 1/2

**Comment by ayazhafiz** [comment]
Sorry, I'm confused. This one?

image

**Comment by luke-bhan** [comment]
the x-x is a clearner vesion, but I was suggesting a different expression not as complex as the frist one but more complex then x-x.

**Comment by ayazhafiz** [comment]
@luke-bhan are you good with this version:

logo

**Comment by luke-bhan** [comment]
yea

**Comment by ayazhafiz** [comment]
@luke-bhan look good to you?

**Comment by luke-bhan** [comment]
Yea I’m really not picky

**Pull request merged**
